feat: export prometheus metrics
uselagoon/storage-calculator pull request #7
Opened 2023-03-02 14:08 UTC by domcyrus

Export prometheus metrics about storage usage. Implements issue #8

2023-03-06 02:51 UTC, shreddedbacon requested changes

2023-03-06 02:51 UTC, shreddedbacon commented on internal/storage/main.go
> +		}).Set(float64(claim.BytesUsed))
I'm not sure how relevant exporting the `type` and `eventType` are, as this is used only by Lagoon to determine how to handle the message. I don't see any reason to capture either of these in the metrics

2023-03-06 02:51 UTC, shreddedbacon commented on main.go
> +		[]string{"type", "eventtype", "claimenv", "claimpvc", "project", "environment"},
as above re `type` and `eventtype`

2023-03-06 07:46 UTC, domcyrus commented
@shreddedbacon I've removed `type` and `eventtype` labels. I've also updated all the dependencies. Is this ok?

2023-03-06 22:25 UTC, shreddedbacon requested changes
You'll also need to update the dockerfile go version used https://github.com/domcyrus/storage-calculator/blob/exportPrometheusMetrics/Dockerfile#L2

2023-03-07 07:20 UTC, shreddedbacon approved these changes

2023-03-07 07:20 UTC, merged